---
- name: 'Add epel repository'
  yum_repository:
    name: epel
    description: EPEL YUM repo
    baseurl: "{{ haproxy_repo }}/$releasever/$basearch/"
  when: haproxy_repo

- name: 'Install HAProxy (yum)'
  yum:
    name: "{{ haproxy_package_name }}"
