---
- name: Include distribution variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
    - default.yml

- name: 'Add epel repository'
  yum_repository:
    name: epel
    description: EPEL YUM repo
    baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
  when: ansible_pkg_mgr == "yum"

- name: Add haproxy apt repo (jessie)
  apt_repository:
    repo: deb http://http.debian.net/debian {{ ansible_distribution_release }} main
    state: present
    update_cache: yes
  when: ansible_distribution_release == 'jessie'

- name: 'Add haproxy apt repo (Ubuntu)'
  apt_repository:
    repo: "ppa:vbernat/haproxy-1.5"
    state: present
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

- name: Install HAProxy (yum)
  yum:
    name: "{{ haproxy_package_name }}"
  when: ansible_pkg_mgr == "yum"

- name: Install HAProxy (apt jessie)
  apt:
    name: "{{ haproxy_package_name }}"
    default_release: "{{ ansible_distribution_release }}"
  when: ansible_distribution_release == 'jessie'

- name: Install HAProxy (Ubuntu)
  package:
    name: "{{ haproxy_package_name }}"
  when: ansible_distribution == 'Ubuntu'

- name: Install supplementary packages
  package:
    name: "{{ item }}"
  with_items: "{{ haproxy_extra_packages }}"

- name: 'Enable it'
  service:
    name: haproxy
    enabled: yes

- name: 'Ensure chroot directory exists'
  file:
    name: "{{ haproxy_global.chroot }}"
    state: directory
  when: haproxy_global.chroot is defined and haproxy_global.chroot
