---
- import_tasks: install.yml

- import_tasks: systemd.yml
  when:
    - ansible_service_mgr == "systemd"
    - not haproxy_svc_unit.stat.exists

- import_tasks: service.yml

- import_tasks: configure.yml
  when: haproxy_manage_config
