---
- include: install.yml

- include: systemd.yml
  when:
    - ansible_service_mgr == "systemd"
    - not haproxy_svc_unit.stat.exists

- include: service.yml

- include: configure.yml
  when: haproxy_manage_config
